### ISSUE TITLE
Query on video demo

### ISSUE THREAD

**Issue by junioralive** [Ciarands/eplayers-resolver#1]
I'm building a command line streaming service i wanted something light weight like the video demo you have shown, this could help me a lot also check my project here https://github.com/junioralive/spy-cli.

**Comment by Ciarands** [comment]
Hey, id be happy to send you the src! 
I'm currently not in my home country and don't have access to my desktop where the src is saved, if you want to reach out to me on discord its "ciaran_ds" and I can send that over when I get home.

**Comment by junioralive** [comment]
Sounds Great! I have sent you a request on discord lets connect there. Thank you!!
